### ISSUE TITLE
Cannot insert into column "id"

### ISSUE THREAD

**Issue by imomin** [ThibTrip/pangres#60] opened 2022-04-05 15:32 UTC
I was testing pangres by simply read from database, loading data in DataFrame and passing to upsert function.
```
query = "select * from \"stocks\" where (symbol = '{0}')".format(ticker)
df = pd.DataFrame(pd.read_sql_query(query ,con=engine, index_col="id"))
upsert(con=engine, df=df, table_name='stocks', if_row_exists='update', create_table=False, add_new_columns=True)

```

> psycopg2.errors.GeneratedAlways: cannot insert into column "id"
> DETAIL:  Column "id" is an identity column defined as GENERATED ALWAYS.
> HINT:  Use OVERRIDING SYSTEM VALUE to override.
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "main.py", line 230, in <module>
>     addReadData(df_)
>   File "main.py", line 158, in addStockData
>     upsert(con=engine, df=data, table_name='stocks', if_row_exists='update', create_table=False, add_new_columns=True)

I assume, it would use index Id as a reference. If Id exists then it should update records or insert. Any idea to resolve this issue?

**Comment by ThibTrip** [comment] 2022-04-06 21:24
Hello @imomin ! Thanks for posting the issue. I will try to reproduce it as soon as I can (which would be this weekend...).

It seems to me that the column `id` is computed. See [example](https://docs.sqlalchemy.org/en/14/core/defaults.html#computed-columns-generated-always-as) in sqlalchemy documentation.

Because of that I wonder if using an SQL query with `ON CONFLICT UPDATE|DO NOTHING` based on this column can work at all. I found for instance this [post](https://stackoverflow.com/q/68963295) which is not very promising.

Perhaps it'll work if in `df` you only have ids that already exist. You'd have to make 1 upsert query for existing records and 1 insert query for non existing records.
In the insert query you would not have the `id` column as the values will be generated by the database.

So yeah I'll have to test that. Unless you figure that out before me that is 🙈.

**Comment by imomin** [comment] 2022-04-06 21:35
@ThibTrip, thanks I ended up dropping `id` from dataframe. I was able to move on but now I have different error `'Key length (2) was greater than MultiIndex lexsort depth (1)'`. I haven't got a chance to debug it yet. I have unique constraints based on 2 columns and I believe it has to do it.

EDIT:
I was able to resolve `Key length (2) ...` error with the following line `df.sort_index(inplace=True)`.

**Comment by ThibTrip** [comment] 2022-04-09 17:06
Hi @imomin, can I still help you with anything 🙂? Otherwise I'd close the issue

**Comment by imomin** [comment] 2022-04-09 17:28
Please close.

**Closed as completed** 2022-04-09 17:29 UTC
