### ISSUE TITLE
Logging set up in utils.py can conflict with logging profiles in calling script

### ISSUE THREAD

**Issue by chrisdunley** [ThibTrip/pangres#18] opened 2020-09-23 11:42 UTC
I have found that importing pangres stops my existing logging setup from working.  I suspect (though am no expert) that the import initialises pangres' logging set up ahead of the calling application and therefore overrides it.  
Is there any reason to have the logging set up in place within the module rather than in the calling application?
Simply removing the logging lines from utils.py seems to do the trick (as does setting up the application logging ahead of importing pangres).

Thanks
Chris

**Comment by ThibTrip** [comment] 2020-09-26 16:31
Hello @chrisdunley ! Thanks for posting the issue and sorry for the late reply. To be honest with you I almost never use <code>logging</code> and use [loguru](https://github.com/Delgan/loguru) instead (can highly recommand it). Obviously adding a dependency for so little use would be nonsense which is why I used <code>logging</code> in <code>pangres</code>.

Anyhow, if my understanding is correct I should set up a new console logging handler and format this handler instead of formatting logging. Seems logic it would seep through your script, sorry about that 😔! 

I'll make a PR as soon as I figure it out.

**Comment by ThibTrip** [comment] 2020-09-26 17:10
@chrisdunley the issue should be fixed :+1: (see screenshot below)! Do you mind using the master branch to see if it works for your application (don't see why it would not but I prefer to be careful)? And then I'd like to create a new minor version.
  
![pangres_bug_logging](https://user-images.githubusercontent.com/40694343/94346234-85019800-002b-11eb-86e5-c8fbdf244344.png)
_logging bug with pangres: on the left side (before PR #19) the logger of our application uses the formatting of the pangres logger (this is a bug) and on the right side (after PR #19) it does not use any formatting (we have not set up any)_

**Comment by ThibTrip** [comment] 2020-10-05 21:16
Hello! Sorry for taking a long time to reply again :turtle:. So if I understand correctly what you expect is this: 
> logged items come through to the log file regardless of whey they originated.

It took some time to understand what you meant but I think I was able to reproduce the issue:

![image](https://user-images.githubusercontent.com/40694343/95131331-27bdc300-075e-11eb-9a81-49e772303c0d.png)

![image](https://user-images.githubusercontent.com/40694343/95132419-078f0380-0760-11eb-88eb-605b4404ad02.png)

_Note: I tested with Python files using [jupytext](https://github.com/mwouts/jupytext) and then the terminal to make sure IPython does not introduce unexpected behaviors_

> I may be missing something here, but is there any reason to define loggers etc in the module?  Presumably that can be left to the main script to setup if required - the module just raising the usual logging.info <http://logging.info/> etc messages as required.

FYI we need logging in 3 places:

* in the [utils.py](https://github.com/ThibTrip/pangres/blob/master/pangres/utils.py#L114) module to indicate a column has been renamed in the function <code>fix_psycopg2_bad_cols</code>
* in the [helpers.py](https://github.com/ThibTrip/pangres/blob/master/pangres/helpers.py#L270-L271) module to indicate a column has been added
* in the [helpers.py](https://github.com/ThibTrip/pangres/blob/master/pangres/helpers.py#L374-L376) module to indicate the SQL data type has been changed for an empty column

I think I am starting to understand the problem :thinking: . So I wanted a pretty logging format for the user of pangres which is why I defined some loggers myself. If I understand correctly I should not do that. I should use the logging library directly and leave the formatting to pangres' user.

I'll try that tomorrow it is very late already I have to get some sleep :turtle:. If you have any thoughts about this or I forgot something please tell me. I am reopening this issue since there is still a problem to fix obviously :neutral_face:. This should be easy to fix I suppose though. I just need to do something like <code>logger = logging.getLogger(\_\_name\_\_)</code>. Just like in the [urllib3](https://github.com/urllib3/urllib3/blob/master/src/urllib3/connectionpool.py#L54) library.

**Comment by ThibTrip** [comment] 2020-10-11 21:26
Hello again @chrisdunley. Unfortunately it was not as simple as I imagined. But I think my last PR (see #21) fixes it.

![image](https://user-images.githubusercontent.com/40694343/95689975-d9ed0300-0c14-11eb-9742-bb53bb0c1909.png)

I will now merge the PR. Feel free to reopen the issue if something still isn't as expected. I took the liberty of creating a new version. It will be out soon.

**Closed as completed** 2020-10-11 21:27 UTC
