### ISSUE TITLE
Postgres upsert with only partial column list specified fails

### ISSUE THREAD

**Issue by DeflateAwning** [ThibTrip/pangres#72] opened 2023-04-06 19:50 UTC
I'm trying to run an upsert with `pangres.upsert(df, ..., if_row_exists='update', chunksize=1)`.

`df` only contains 3 out of 25 columns in the SQL table. `df`'s index is `pn_well_id`.

The upsert errors with a SQL script like:
```sql
INSERT INTO schema_name.table_name (pn_well_id, formation, formation_top_code, formation_bottom_code)
VALUES ('AB007850300', 'Milk River', 158000000.0, 158000000.0)
ON CONFLICT (pn_well_id)
DO UPDATE SET formation = excluded.formation, formation_top_code = excluded.formation_top_code, formation_bottom_code = excluded.formation_bottom_code
```

Note that the SQL script's parameters were replaced with hard coding for debugging.

However, when run in Postgres, there is an error saying that `other_column_in_table_with_not_null_constraint` is trying to be set to NULL.

```
SQL Error [23502]: ERROR: null value in column "other_column_in_table_with_not_null_constraint" violates not-null constraint
  Detail: Failing row contains (19950939, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, Milk River, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, AB007850300, null, null, null, null, null, null, null, null, 2023-04-06 13:50:03.086709, null, null, null, null, null, null, null, null, null, 158000000, 158000000).
```

My understanding is that it `other_column_in_table_with_not_null_constraint` should maintain its current value, and the specified columns (formation, formation_top_code, formation_bottom_code) should be updated. Instead, it gives an error like:

There is a unique key in the table on the `pn_well_id` column.

**Comment by ThibTrip** [comment] 2023-04-07 20:32
Hi @DeflateAwning I think I understand the problem. The SQL query should reuse existing values in order to satisfy `NOT NULL` SQL constraints.

> When an `UPDATE` is performed as part of the `ON CONFLICT` clause, PostgreSQL treats the row being
> updated as if it were being deleted and a new row was being inserted with the specified changes.
>
> As a result, all the columns not explicitly mentioned in the `DO UPDATE` clause are set to their default values. In the 
> case of columns with a NOT NULL constraint and no default value, this behavior leads to a constraint violation, and an error is raised.
>
> _Thanks ChatGPT 4 :see_no_evil:_

The SQL query would have to look like that:

```sql
INSERT INTO schema_name.table_name (pn_well_id, formation, formation_top_code, formation_bottom_code)
VALUES ('AB007850300', 'Milk River', 158000000.0, 158000000.0)
ON CONFLICT (pn_well_id)
DO UPDATE SET
    formation = excluded.formation,
    formation_top_code = excluded.formation_top_code,
    formation_bottom_code = excluded.formation_bottom_code,
    other_column_in_table_with_not_null_constraint = table_name.other_column_in_table_with_not_null_constraint
```

The problem is that this falls out of scope of the library I'm afraid. Even if I added an optional parameter (e.g. `non_null_columns: Iterable[str] = None`) to generate SQL queries like the above, I'm not sure this would cover all cases :thinking: .

I could suggest these solutions for now:
1. Use `sqlalchemy` directly using your own query. You can check out the module [upsert_query](https://github.com/ThibTrip/pangres/blob/master/pangres/upsert_query.py) which contains most of the logic you need.
2. Somehow providing `other_column_in_table_with_not_null_constraint`. E.g. there are no concurrent updates, you could read values from the database before the upsert operation.

Please let me know about future developments regarding your issue. Perhaps there is a solution for this library after all. Please note I don't have a lot of time atm (and in general unfortunately).

**Comment by DeflateAwning** [comment] 2023-04-07 20:40
Are you sure there's no way to make Postgresql check for the conflict first. The query succeeds if there are no `NOT NULL` constraints (i.e., all columns can be set to null)?

**Comment by ThibTrip** [comment] 2023-04-07 20:49
> Are you sure there's no way to make Postgresql check for the conflict first

Not to my knowledge sorry :(.

> The query succeeds if there are no NOT NULL constraints (i.e., all columns can be set to null)?

Yeah it should work if there are no `NOT NULL` constraints :)

**Closed as not planned** 2023-10-03 17:28 UTC
